---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cspc-operator
  namespace: openebs
  labels:
    name: cspc-operator
    openebs.io/component-name: cspc-operator
    openebs.io/version: dev
spec:
  selector:
    matchLabels:
      name: cspc-operator
      openebs.io/component-name: cspc-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cspc-operator
        openebs.io/component-name: cspc-operator
        openebs.io/version: dev
    spec:
      serviceAccountName: openebs-cstor-operator
      containers:
      - name: cspc-operator
        imagePullPolicy: IfNotPresent
        image: openebs/cspc-operator:ci
        env:
        - name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENEBS_SERVICEACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CSPC_OPERATOR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # OPENEBS_IO_BASE_DIR is used to configure base directory for openebs on host path.
        # Where OpenEBS can store required files. Default base path will be /var/openebs
        # - name: OPENEBS_IO_BASE_DIR
        #   value: "/var/openebs"
        # OPENEBS_IO_CSTOR_POOL_SPARSE_DIR can be used to specify the hostpath
        # to be used for saving the shared content between the side cars
        # of cstor pool pod. This ENV is also used to indicate the location
        # of the sparse devices.
        # The default path used is /var/openebs/sparse
        #- name: OPENEBS_IO_CSTOR_POOL_SPARSE_DIR
        #  value: "/var/openebs/sparse"
        #  OPENEBS_IO_IMAGE_PULL_SECRETS is used to specify the image pull secrets for the cstor pool pod
        #- name: OPENEBS_IO_IMAGE_PULL_SECRETS
        #  value: ""
        - name: OPENEBS_IO_CSPI_MGMT_IMAGE
          value: "openebs/cstor-pool-manager:ci"
        - name: OPENEBS_IO_CSTOR_POOL_IMAGE
          value: "openebs/cstor-pool:ci"
        - name:  OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE
          value: "openebs/m-exporter:ci"
        - name: RESYNC_INTERVAL
          value: "30"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvc-operator
  namespace: openebs
  labels:
    name: cvc-operator
    openebs.io/component-name: cvc-operator
    openebs.io/version: dev
spec:
  selector:
    matchLabels:
      name: cvc-operator
      openebs.io/component-name: cvc-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cvc-operator
        openebs.io/component-name: cvc-operator
        openebs.io/version: dev
    spec:
      serviceAccountName: openebs-cstor-operator
      containers:
      - name: cvc-operator
        imagePullPolicy: IfNotPresent
        image: openebs/cvc-operator:ci
        args:
          - "--v=2"
          - "--leader-election=false"
          - "--bind=$(OPENEBS_CVC_POD_IP)"
        env:
        # OPENEBS_IO_BASE_DIR is used to configure base directory for openebs on host path.
        # Where OpenEBS can store required files. Default base path will be /var/openebs
        # - name: OPENEBS_IO_BASE_DIR
        #   value: "/var/openebs"
        # OPENEBS_IO_CSTOR_TARGET_DIR can be used to specify the hostpath
        # that to be used for saving the core dump of cstor volume pod.
        # The default path used is /var/openebs/sparse
        #- name: OPENEBS_IO_CSTOR_TARGET_DIR
        #  value: "/var/openebs/sparse"
        #  OPENEBS_IO_IMAGE_PULL_SECRETS is used to specify the image pull secrets for the cstor target pod
        #- name: OPENEBS_IO_IMAGE_PULL_SECRETS
        #  value: ""
        - name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENEBS_CVC_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OPENEBS_SERVICEACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: OPENEBS_IO_CSTOR_TARGET_IMAGE
          value: "openebs/cstor-istgt:ci"
        - name:  OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE
          value: "openebs/cstor-volume-manager:ci"
        - name:  OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "openebs/m-exporter:ci"
---
apiVersion: v1
kind: Service
metadata:
  name: cvc-operator-service
  namespace: openebs
  labels:
    openebs.io/component-name: cvc-operator-svc
spec:
  ports:
  - name: api
    port: 5757
    protocol: TCP
    targetPort: 5757
  selector:
    name: cvc-operator
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-cstor-admission-server
  namespace: openebs
  labels:
    app: cstor-admission-webhook
    openebs.io/component-name: cstor-admission-webhook
    openebs.io/version: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: cstor-admission-webhook
  template:
    metadata:
      labels:
        app: cstor-admission-webhook
        openebs.io/component-name: cstor-admission-webhook
        openebs.io/version: dev
    spec:
      serviceAccountName: openebs-cstor-operator
      containers:
        - name: admission-webhook
          image: openebs/cstor-webhook:ci
          imagePullPolicy: IfNotPresent
          args:
            - -alsologtostderr
            - -v=2
            - 2>&1
          env:
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ADMISSION_WEBHOOK_NAME
              value: "openebs-cstor-admission-server"
            - name: ADMISSION_WEBHOOK_FAILURE_POLICY
              value: "Fail"
