---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cstorpoolinstances.cstor.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: cstor.openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cstorpoolinstances
    # singular name to be used as an alias on the CLI and for display
    singular: cstorpoolinstance
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CStorPoolInstance
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - cspi
  additionalPrinterColumns:
    - JSONPath: .spec.hostName
      name: HostName
      description: Host name where cstorpool instances scheduled
      type: string
    - JSONPath: .status.capacity.used
      name: Allocated
      description: The amount of storage space within the pool that has been physically allocated
      type: string
    - JSONPath: .status.capacity.free
      name: Free
      description: The amount of usable free space available in the pool
      type: string
    - JSONPath: .status.capacity.total
      name: Capacity
      description: Total amount of usable space in pool
      type: string
    - JSONPath: .status.readOnly
      name: ReadOnly
      description: Identifies the pool read only mode
      type: boolean
    - JSONPath: .spec.poolConfig.dataRaidGroupType
      name: Type
      description: The type of the storage pool
      type: string
    - JSONPath: .status.phase
      name: Status
      description: Identifies the current health of the pool
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
---
