---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cstorvolumes.cstor.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: cstor.openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CStorVolume
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cstorvolumes
    # singular name to be used as an alias on the CLI and for display
    singular: cstorvolume
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cstorvolume
    - cv
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    description: Identifies the current health of the target
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.capacity
    description: Current volume capacity
    name: Capacity
    type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cstorvolumeclaims.cstor.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: cstor.openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CStorVolumeClaim
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cstorvolumeclaims
    # singular name to be used as an alias on the CLI and for display
    singular: cstorvolumeclaim
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cstorvolumeclaim
    - cvc
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    description: Identifies the current health of the target
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cstorvolumepolicies.cstor.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: cstor.openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CStorVolumePolicy
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cstorvolumepolicies
    # singular name to be used as an alias on the CLI and for display
    singular: cstorvolumepolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cstorvolumepolicies
    - cvp
    - policy
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    description: Identifies the current health of the target
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cstorvolumereplicas.cstor.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: cstor.openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CStorVolumeReplica
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cstorvolumereplicas
    # singular name to be used as an alias on the CLI and for display
    singular: cstorvolumereplica
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cvr
  additionalPrinterColumns:
  - JSONPath: .status.capacity.used
    name: Used
    description: The amount of space that is "logically" consumed by this dataset
    type: string
  - JSONPath: .status.capacity.totalAllocated
    name: Allocated
    description: The amount of disk space consumed by a dataset and all its descendents
    type: string
  - JSONPath: .status.phase
    name: Status
    description: Identifies the current health of the replicas
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
